### ISSUE TITLE
Error importing packages based on documentation

### ISSUE THREAD

**Issue by davidparks21** [rjw57/videosequence#2]
I'm trying to import the basics based on the documentation here:

```
from contextlib import closing
from videosequence import VideoSequence
```
At first it was missing the package `gi`. 

Assuming this is the appropriate thing to install, it's at the latest version 3.20.0:

```
sudo apt install python-gi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-gi is already the newest version (3.20.0-0ubuntu1).
The following packages were automatically installed and are no longer required:
  libcublas7.5 libcudart7.5 libcufft7.5 libcufftw7.5 libcuinj64-7.5 libcurand7.5 libcusolver7.5 libcusparse7.5
  libkexiv2-11v5 libkexiv2-data libnppc7.5 libnppi7.5 libnpps7.5 libnvblas7.5 libnvrtc7.5 libnvtoolsext1 libnvvm3
  libokularcore7 libpoppler-qt4-4 libqimageblitz4 libqmobipocket1 libthrust-dev nvidia-opencl-dev nvidia-profiler
  opencl-headers
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.
```

I also tried to pip install the `gi` python package, though it wasn't mention in the docs, it certainly appears to be a a dependency. But it doesn't appear to be the right course of action:

```
__init__.py in <module>()
     10 import PIL.Image as Image
     11 
---> 12 gi.require_version('Gst', '1.0')
     13 gi.require_version('GstApp', '1.0')
     14 from gi.repository import Gst, GstApp

AttributeError: 'module' object has no attribute 'require_version'
```

At this point I'm not clear what the dependencies are for the package.

**Comment by rjw57** [comment]
Thanks for taking the time to give some feedback.

> Assuming this is the appropriate thing to install, it's at the latest version 3.20.0:

Did you install the other packages mentioned in the README? The list of packages for Debian/Ubuntu-based distros is given as: gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 python-gi python3-gi libgstreamer1.0-dev gstreamer1.0-plugins-good. See https://github.com/rjw57/videosequence#ubuntu-and-debian

On a brand new Ubuntu VM after installing those packages and python-pip, I can install and import the library without problem:

```
Singularity ubuntu.img:~/Downloads> pip install --user videosequence
[...]
Successfully installed future-0.16.0 olefile-0.44 pillow-4.2.1 videosequence-1.1.0
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Singularity ubuntu.img:~/Downloads> python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from videosequence import VideoSequence
>>> 
Singularity ubuntu.img:~/Downloads> 
```
This is with the same version of python-gi as you installed:
```
Singularity ubuntu.img:~/Downloads> apt show python-gi
Package: python-gi
Version: 3.20.0-0ubuntu1
Priority: optional
Section: python
Source: pygobject
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Josselin Mouette <joss@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 693 kB
Provides: python2.7-gi
Depends: python (<< 2.8), python (>= 2.7~), python:any (>= 2.7.5-5~), libc6 (>= 2.14), libffi6 (>= 3.0.4), libgirepository-1.0-1 (>= 1.44.0), libglib2.0-0 (>= 2.41.1), gir1.2-glib-2.0 (>= 1.39.0)
Suggests: python-gi-cairo
Breaks: python-aptdaemon (<< 1.0), software-center (<= 5.6.0-0ubuntu2)
Homepage: https://wiki.gnome.org/Projects/PyGObject
Task: edubuntu-desktop-gnome, mythbuntu-frontend, mythbuntu-desktop, mythbuntu-backend-slave, mythbuntu-backend-master, lubuntu-desktop, ubuntustudio-video, ubuntustudio-publishing, ubuntustudio-photography, ubuntustudio-graphics, ubuntustudio-audio, ubuntu-gnome-desktop, ubuntu-sdk, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-mate-cloudtop
Supported: 5y
Download-Size: 194 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
Description: Python 2.x bindings for gobject-introspection libraries
```
So I'm afraid I can't reproduce the issue as reported. Can you confirm if you have all the packaged mentioned in the documentation installed?

Thanks

**Comment by bml1g12** [comment]
Using ubuntu 20, a fresh anaconda Python 3.7 VM and installing all the README requirements, I get
```
Traceback (most recent call last):
  File "decord_test_opencv.py", line 245, in <module>
    draw_frame(
  File "decord_test_opencv.py", line 35, in draw_frame
    from videosequence import VideoSequence
  File "/home/ben/.local/lib/python3.8/site-packages/videosequence/__init__.py", line 9, in <module>
    import gi
```
